[phases.setup]
nixPkgs = ["php82", "composer", "mysql", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
